patch: update dependencies
Note to the reviewer:

A) `org.apache.maven.plugings:maven-javadoc-plugin` is only update to 2.7.
   In theory it could go to 3.1.1 but the `<additionalOptions>-html5</additionalOptions>` configuration option does not work.

B) In IntelliJ I get the following error:

```
jamod build failed
  ModbusTCPTransport.jav
java: cannot access java.util.stream.Stream
  class file for java.util.stream.Stream not found
```

When I run 'mvn package' I get the following error:
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Source option 7 is no longer supported. Use 8 or later.
[ERROR] Target option 7 is no longer supported. Use 8 or later.
[INFO] 2 errors
```